# Generated by Django 3.2.5 on 2022-11-01 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('country', models.CharField(choices=[('Россия', 'Россия'), ('Казахстан', 'Казахстан'), ('Белоруссия', 'Белоруссия'), ('Украина', 'Украина')], max_length=30, verbose_name='Страна')),
                ('year', models.CharField(choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=30, verbose_name='Год')),
                ('month', models.CharField(choices=[('январь', 'январь'), ('февраль', 'февраль'), ('март', 'март'), ('апрель', 'апрель'), ('май', 'май'), ('июнь', 'июнь'), ('июль', 'июль'), ('август', 'август'), ('сентябрь', 'сентябрь'), ('октябрь', 'октябрь'), ('ноябрь', 'ноябрь'), ('декабрь', 'декабрь')], max_length=30, verbose_name='месяц')),
                ('direction', models.CharField(choices=[('суставы', 'суставы'), ('потенция', 'потенция'), ('похудение', 'похудение'), ('вальгусы', 'вальгусы'), ('грибки', 'грибки'), ('гипертония', 'гипертония'), ('диабет', 'диабет'), ('красота', 'красота'), ('паразиты', 'паразиты'), ('вальгусы', 'вальгусы'), ('грибки', 'грибки'), ('гипертония', 'гипертония')], max_length=30, verbose_name='Направление')),
                ('price', models.IntegerField(verbose_name='Цена (в рублях)')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='Внешний ID пользователя')),
                ('name', models.TextField(verbose_name='Имя пользователя')),
                ('order_msg_id', models.PositiveIntegerField(verbose_name='ID сообщения с заказом')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='ProductChoice',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('country', models.CharField(choices=[('Россия', 'Россия'), ('Казахстан', 'Казахстан'), ('Белоруссия', 'Белоруссия'), ('Украина', 'Украина')], max_length=30, verbose_name='Страна')),
                ('year', models.CharField(choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=30, verbose_name='Год')),
                ('month', models.CharField(choices=[('январь', 'январь'), ('февраль', 'февраль'), ('март', 'март'), ('апрель', 'апрель'), ('май', 'май'), ('июнь', 'июнь'), ('июль', 'июль'), ('август', 'август'), ('сентябрь', 'сентябрь'), ('октябрь', 'октябрь'), ('ноябрь', 'ноябрь'), ('декабрь', 'декабрь')], max_length=30, verbose_name='месяц')),
                ('direction', models.CharField(choices=[('суставы', 'суставы'), ('потенция', 'потенция'), ('похудение', 'похудение'), ('вальгусы', 'вальгусы'), ('грибки', 'грибки'), ('гипертония', 'гипертония'), ('диабет', 'диабет'), ('красота', 'красота'), ('паразиты', 'паразиты'), ('вальгусы', 'вальгусы'), ('грибки', 'грибки'), ('гипертония', 'гипертония')], max_length=30, verbose_name='Направление')),
                ('payment_method', models.CharField(choices=[('Картой', 'Картой'), ('Криптовалютой', 'Криптовалютой')], max_length=30, verbose_name='Способ оплаты')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ugc.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время получения')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
