# Generated by Django 3.2.5 on 2022-11-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='order_msg_id',
            field=models.PositiveIntegerField(blank=True, verbose_name='ID сообщения с заказом'),
        ),
    ]
