# Generated by Django 3.2.5 on 2022-11-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_id',
            field=models.TextField(null=True, verbose_name='ID счета оплаты'),
        ),
    ]
