# Generated by Django 3.2.5 on 2022-11-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_alter_profile_order_msg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
