# Generated by Django 3.2.5 on 2022-11-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='order_msg',
            field=models.TextField(null=True, verbose_name='Сообщение заказа'),
        ),
    ]
