# Generated by Django 3.2.5 on 2022-11-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0005_profile_order_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='order_msg',
            field=models.TextField(default='', verbose_name='Сообщение заказа'),
        ),
    ]
